### ISSUE TITLE
Update pina-golada version

### ISSUE THREAD

**Issue by lynxplay** [homeport/homebrew-tap#1]
After implementing the integration test in pina-golada version 1.4.0 as well as upgrading to 1.12 golang, the brew tap should represent that change as it will be the base version everyone should use as its functionality is ensured by the integration test.

**Comment by HeavyWombat** [comment]
Done with https://github.com/homeport/homebrew-tap/commit/d8db26d690c43fb1d7fb6d9a5bfb3016791d6512
