### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by yermulnik** [homeport/homebrew-tap#48]
Please add conditional install of `dyff-linux-amd64` on Linux into Formula.
Thanks in advance.

**Comment by HeavyWombat** [comment]
@yermulnik Thanks for the hint. I kind of missed this issue, so sorry for the delayed response. There are plans to switch to GoReleaser for `dyff` and that will introduce the Linux section by default -- I think.

**Comment by yermulnik** [comment]
Does `GoReleaser` manage also brew formulaes for the projects where it's used to release binaries? 🤔 
I meant specifically brew formulae flavour since `dyff` already builds linux binaries. E.g. like this: https://github.com/minamijoyo/homebrew-tfupdate/blob/master/tfupdate.rb

**Comment by yermulnik** [comment]
Oh, nvm me, I've found `GoReleaser` can indeed take care of `brew` formulas: https://goreleaser.com/customization/homebrew/

**Comment by HeavyWombat** [comment]
@yermulnik Can you have a look at the new version? The build and Homebrew tap was done by GoReleaser. It now includes a section for the Linux download.

**Comment by yermulnik** [comment]
yay! marvelous! thanks a bunch! :bow: 
```
> file $(realpath $(brew --prefix)/bin/dyff)
/home/linuxbrew/.linuxbrew/Cellar/dyff/1.2.1/bin/dyff: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped

> dyff version
dyff version 1.2.1
```
